# Generated by Django 2.1 on 2019-07-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aaproved_comment',
            new_name='approved_comment',
        ),
    ]
